# 应用名称
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/17721541089/springcloud-yys2.git #配置文件所在仓库
          search-paths: configserver
          default-label: master #配置文件分支
          username: 17721541089 #登录账号
          password: sheng6130219 #登录密码


server:
  port: 8888





